## 4.2
### the equation
### $ a^{3} + b^{3} = c^{2} $
### has integer solutions such that $ c>=b>=a>=1 $

### one solution is (a, b, c) = (2, 2, 4)

In [1]:
import pandas as pd

def doesWork(a, b, c):
    return a**3 + b**3 == c**2

def generateTable(ar, br, cr): #ranges for each
    d={"A": [],"B": [], "C": []}
    for i in range(1, ar+1):
        for j in range(i, br+1):
            for k in range(j, cr+1):
                if doesWork(i, j, k):
                    d["A"].append(i)
                    d["B"].append(j)
                    d["C"].append(k)
    return pd.DataFrame(d)

In [2]:
DF1=generateTable(100, 100, 150)
display(DF1)

    A   B    C
0   1   2    3
1   2   2    4
2   4   8   24
3   7  21   98
4   8   8   32
5   9  18   81
6  18  18  108

## ok so that didnt give a ton of good results
## lets try again, but folloing form (a, b, c)=(xz, yz, z^2)

In [3]:
def generateABC(xr, yr, zr):
    d={"X":[], "Y": [], "Z":[], "A": [],"B": [], "C": []}
    for i in range(1, xr+1):
        for j in range(i, yr+1):
            for k in range(j, zr+1):
                a=i*k
                b=j*k
                c=k**2
                if doesWork(a, b, c):
                    d["A"].append(a)
                    d["B"].append(b)
                    d["C"].append(c)
                    d["X"].append(i)
                    d["Y"].append(j)
                    d["Z"].append(k)
    return pd.DataFrame(d)

In [4]:
DF2=generateABC(100, 100, 150)
display(DF2)

    X  Y    Z    A    B      C
0   1  1    2    2    2      4
1   1  2    9    9   18     81
2   1  3   28   28   84    784
3   1  4   65   65  260   4225
4   1  5  126  126  630  15876
5   2  2   16   32   32    256
6   2  3   35   70  105   1225
7   2  4   72  144  288   5184
8   2  5  133  266  665  17689
9   3  3   54  162  162   2916
10  3  4   91  273  364   8281
11  4  4  128  512  512  16384

# 4.2 (a)
## (2, 2, 4), (9, 18, 81), (28, 84, 784), (32, 32, 256)
#### extra ones that dont fit (xz, yz, zz) = (8, 8, 32), (4, 8, 24), (1, 2, 3)

# 4.2 (c)
## write 4 primitive solutions
### primitive does not look like $ (n^{2}*A, n^{2}*B, n^{3}*C) $

In [5]:
import math
def isPrimitive(a, b, c):
    for i in range(2, math.floor(math.sqrt(a))+1):
        if a%(i**2)==0 and b%(i**2)==0 and c%(i**3)==0:
            return False
    return True

def generatePrimitive(maxC):
    Idx=[]
    DF=generateTable(maxC, maxC, maxC)
    for index in DF.index:
        a=DF["A"][index]
        b=DF["B"][index]
        c=DF["C"][index]
        print(f'testing is primitive on {a}, {b}, {c}: {isPrimitive(a, b, c)}')
        if isPrimitive(a, b, c):
            Idx.append(index)
    d={"A": [], "B":[], "C":[]}
    for idx in Idx:
        d["A"].append(DF["A"][idx])
        d["B"].append(DF["B"][idx])
        d["C"].append(DF["C"][idx])
        
    return pd.DataFrame(d)

In [6]:
DF=generatePrimitive(250)
display(DF)

testing is primitive on 1, 2, 3: True
testing is primitive on 2, 2, 4: True
testing is primitive on 4, 8, 24: False
testing is primitive on 7, 21, 98: True
testing is primitive on 8, 8, 32: False
testing is primitive on 9, 18, 81: False
testing is primitive on 11, 37, 228: True
testing is primitive on 16, 32, 192: False
testing is primitive on 18, 18, 108: False
testing is primitive on 22, 26, 168: True

    A   B    C
0   1   2    3
1   2   2    4
2   7  21   98
3  11  37  228
4  22  26  168

## 4.2 (d)
### find primitive solutions where a=b

In [ ]:
def genSpecificPrim(maxC):
    d={"A":[], "B":[], "C":[]}
    for i in range(1, int(maxC/2)):
        for j in range(i, maxC):
            if doesWork(i, i, j):
                if isPrimitive(i, i, j):
                    d["A"].append(i)
                    d["B"].append(i)
                    d["C"].append(j)
            elif 2 * i**3 < j**2:
                break
    return pd.DataFrame(d)

In [ ]:
DF=genSpecificPrim(50000)
display(DF)

## 4.2 (e)
### find primitives where a>10000

In [11]:
def generateBigPrimitives(minA): #ranges for each
    d={"A": [],"B": [], "C": []}
    for i in range(minA, minA*2):
        for j in range(i, minA*2):
            for k in range(j, int(math.sqrt(i**3+j**3))):
                if doesWork(i, j, k):
                    if isPrimitive(i, j, k):
                        print(f'working prim: {(i, j, k)}')
                        d["A"].append(i)
                        d["B"].append(j)
                        d["C"].append(k)
                elif i**3 + j**3 < k**2:
                    break
    return pd.DataFrame(d)

In [12]:
DF=generateBigPrimitives(10000)
display(DF)

KeyboardInterrupt: